# Generated by Django 5.2.9 on 2026-04-15 16:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('pageindex_id', models.CharField(blank=True, max_length=255, null=True)),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('UPLOADING', '上传中'), ('INDEXING', '索引中'), ('COMPLETED', '完成'), ('FAILED', '失败')], default='UPLOADING', max_length=20)),
                ('workspace_id', models.UUIDField(default=uuid.uuid4)),
            ],
            options={
                'ordering': ['-upload_time'],
            },
        ),
    ]
