# Generated by Django 6.0.4 on 2026-04-15 02:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Model",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("model_type", models.CharField(max_length=64)),
                ("model_name", models.CharField(max_length=256)),
                ("provider", models.CharField(max_length=256)),
                ("credential", models.TextField()),
                ("status", models.CharField(default="VALID", max_length=64)),
                ("workspace_id", models.UUIDField()),
                ("model_params_setting", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "model",
                "unique_together": {("name", "workspace_id")},
            },
        ),
    ]
